
CREATE TABLE IF NOT EXISTS public.tb_categoria_evento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tb_categoria_evento_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.tb_evento
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    artistas character varying(255) COLLATE pg_catalog."default",
    data_hora_inicio timestamp(6) without time zone,
    data_hora_termino timestamp(6) without time zone,
    descricao character varying(255) COLLATE pg_catalog."default",
    latitude double precision,
    longitude double precision,
    preco numeric(38,2),
    titulo character varying(255) COLLATE pg_catalog."default",
    id_categoria bigint,
    CONSTRAINT tb_evento_pkey PRIMARY KEY (id),
    CONSTRAINT fkd1in1jy3b20ngwuo1168rg4d5 FOREIGN KEY (id_categoria)
        REFERENCES public.tb_categoria_evento (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;


CREATE TABLE IF NOT EXISTS public.tb_url_imagem
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    url character varying(255) COLLATE pg_catalog."default",
    id_evento bigint NOT NULL,
    CONSTRAINT tb_url_imagem_pkey PRIMARY KEY (id),
    CONSTRAINT fk55lutgbpkgnjjs1effvpwpeut FOREIGN KEY (id_evento)
        REFERENCES public.tb_evento (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;
